- name: Clean OpenStack deployment
  hosts: "{{ target_host | default('localhost') }}"
  tasks:
    - name: Clean up OpenStack operators
      vars:
        cifmw_kustomize_deploy_keep_generated_crs: false
      ansible.builtin.include_role:
        name: kustomize_deploy
        tasks_from: cleanup

    - name: Remove logs and tests directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/home/zuul/ci-framework-data/logs"
        - "/home/zuul/ci-framework-data/tests"
      become: true
